#!/usr/bin/env python
"""
Created on Thu Apr 27 11:24:22 2017

@author: Jonathan Lym
"""

import argparse
from warnings import warn
from os import getcwd, chdir
from os.path import isdir, exists

#Parse arguments
parser = argparse.ArgumentParser(description = "Checks the paths in joblist.txt and folderlist.txt to ensure they exist for Job Array Submission.")
parser.add_argument("job_file", default = './joblist.txt', help = "File that contains job names.")
parser.add_argument("folder_file", default = './folderlist.txt', help = "File that contains paths to jobs.")
args = parser.parse_args()
job_file = args.job_file
folder_file = args.folder_file

home_dir = getcwd()
with open(job_file, 'r') as job_ptr, open(folder_file, 'r') as folder_ptr:
    for job, folder in zip(job_ptr, folder_ptr):
        #Check if folder exists
        job = job.replace('\n', '')
        folder = folder.replace('\n', '')
        folder_exists = isdir(folder)
        if folder_exists:
            chdir(folder)
            job_exists = exists('{}.py'.format(job))
            if job_exists:
                print 'Job {}.py at {} exists!'.format(job, folder)
                if 'testRun = True' in open('{}.py'.format(job), 'r').read():
                    warn('testRun = True for job {}.py at {}'.format(job, folder))
            else:
                warn('Job {}.py does not exist at {}.'.format(job, folder))
        else:
            warn('Warning: Folder {} does not exist.'.format(folder))
        chdir(home_dir)
