#!/usr/bin/env python
"""
Created on Thu Apr 27 11:24:22 2017

@author: Jonathan Lym
"""

import argparse
from warnings import warn
from os import getcwd, chdir
from os.path import isdir, exists, splitext, basename

#Parse arguments
parser = argparse.ArgumentParser(description = "Takes the path to the output folder and removes useful lines.")
parser.add_argument("in_path", help = "Holds the path to the input file that will be cleaned.")
parser.add_argument("out_path", nargs='?', default = None, help = "Name of the path where the formatted output will be saved. If nothing is specified, the output file will take the format '[in_file_name]_cleaned.[in_extension]")
args = parser.parse_args()
in_path = args.in_path
out_path = args.out_path

#Lines that will be deleted
del_lines = ['regcache incompatible with malloc',
             'FORTRAN STOP',
             'srun: Job step creation temporarily disabled, retrying',
             'srun: Job step created',
             'DASPK--  AT CURRENT T (=R1)',
             'DASPK--  TAKEN ON THIS CALL BEFORE REACHING TOUT',
             'In above message,  R1 ='
             'Error in mx_open_endpoint (error No MX device entry in /dev.)',
             'more processes have sent help message help-mpi-btl-base.txt / btl:no-nics',
             'Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages',
             'Module: Myrinet/MX',
             ' A high-performance Open MPI point-to-point messaging module',
             'was unable to find any relevant network interfaces',
             'Host: node',
             'Another transport will be used instead, although this may result in',
             'lower performance.']

print 'The following lines will be removed:'
for del_line in del_lines:
    print '\t{}'.format(del_line)

if out_path is None:
    in_name, in_extension = splitext(basename(in_path))
    out_path = '{}_cleaned{}'.format(in_name, in_extension)

i = 0
with open(in_path, 'r') as in_file, open(out_path, 'w') as out_file:
    for line in in_file:
        #If the line does not contain any of the delete phrases
        if not any([del_line in line for del_line in del_lines]):
            #Write it to the output file
            out_file.write(line)
        else:
            i += 1
print 'Removed {} line(s)'.format(i)
