#!/usr/bin/env python

import os
import argparse
from ase.io import read

parser = argparse.ArgumentParser(description = "Iterates through folderlist to find OUTCAR energies.")
parser.add_argument("folder_file", nargs = '?', default = './folderlist.txt', help = "File that contains the folder list of job array. Default is ./folderlist.txt")
args = parser.parse_args()

with open(args.folder_file, 'r') as f_ptr:
    for i, line in enumerate(f_ptr):
        line = line.replace('\n', '')
        try:
            atoms = read(os.path.join(*['.', line, 'OUTCAR']))
        except:
            print 'Line {}  Unable to process {}'.format(i+1, os.path.join(line, 'OUTCAR'))
        else:
            print 'Line {}  {}\t{}'.format(i+1, line, atoms.get_potential_energy())
