#!/usr/bin/env python
"""
Created on Tue Aug 8 11:51:22 2017

@author: Jonathan Lym
"""

import argparse
from ase.io import read
from ase.visualize import view

#Parse arguments
parser = argparse.ArgumentParser(description = "Takes a file and views it using ase.visualize instead of ase-gui.")
parser.add_argument("file_in", help = "File to view.")
args = parser.parse_args()
file_in = args.file_in

view(read(file_in))