#!/usr/bin/env python
"""
Created on Thu Apr 27 11:24:22 2017

@author: Jonathan Lym
"""

import argparse
import os

#Parse arguments
parser = argparse.ArgumentParser(description = "Finds all the .out files in the folder specified and returns any lines starting with 'Energy:'")
parser.add_argument("folder_in", help = "Folder that contains the .out file.")
args = parser.parse_args()
folder_in = args.folder_in

for root, folders, files in os.walk(folder_in):
    for file in files:
        if '.out' in file:
            with open(os.path.join(root, file), 'r') as f_ptr:
                for line in f_ptr:
                    if 'Energy: ' in line:
                        print '{}\t{}'.format(os.path.join(root, file), line.replace('\n', ''))
