#!/usr/bin/env python
import argparse
from ase.io import read, write
from ase.visualize import view

parser = argparse.ArgumentParser(description='Takes a file and moves the atoms based on the cell.')
parser.add_argument('path_in', type = str, help = '<Required> Location the file will be read.')
parser.add_argument('-i', '--indices', nargs = '+', help = '<Required> List of atom indices.')
parser.add_argument('-c', '--cell', nargs = '+', help = 'Cell dimension to use to move the atoms.')
parser.add_argument('-o', '--offset', nargs = '+', help = 'Direction and offset for cell dimensions.')

args = parser.parse_args()

#Read file
atoms = read(args.path_in)

#Move atoms
for (i, cell, offset) in zip(args.indices, args.cell, args.offset):
    cell_dir = offset*atoms.get_cell()[abs(cell_i)]
    print "Moving atom {}{} by {}}".format(atoms[i].symbol, i, np.array_str(cell_dir))
    atoms_obj[i].position += cell_dir

#Output
view(atoms_obj)
print "Overwrite {} (Y/N)?".format(in_path)
overwrite = raw_input('>>')
if overwrite.lower() == 'y':
    out_path = in_path
else:
    out_path = '{}_fix'.format(in_path)
write(out_path, atoms_obj)
print "Completed move_atoms_by_cell."